// User-provided coin names, normalized to Binance base-asset names.
export const ALLOWED_BASE_ASSETS = [
  "BTC", "ETH", "XAUT", "PAXG", "SOL", "SOPH", "AKE", "UNI", "XRP", "ZEC",
  "DOGE", "SLVON", "DOT", "BNB", "SOLV", "PIEVERSE", "LTC", "SNDKB", "LINK", "AVAX",
  "XAN", "INJ", "AAVE", "NVDAX", "DASH", "WLD", "BUSD", "ARB", "VVV", "HYPE", "BCH",
  "BEAT", "PUMP", "SOXLB", "ADA", "FF", "SUI", "CROSS", "RIVER", "TAO", "TAC", "HUSD",
  "FIL", "SKHYB", "MUSD", "QQQX", "ARC", "CHIP", "ZRO", "SPCXX", "MUB", "VELVET",
  "BLESS", "ZORA", "LIT", "XPL", "ETC", "INTCB", "FARTCOIN", "MSTRB", "TSLAX", "KAITO",
  "AIO", "PENDLE", "JUP", "XMR", "SPYX", "SUSHI", "TIA", "TRUMP", "SKYAI", "NEAR",
  "CRCLX", "NBISB", "AVAAI", "ONDO", "MRVLB", "ASTER", "CBRSB", "JTO", "CAKE", "AAPLX",
  "METAX", "HOODB", "PLTRB", "ENA", "GIGGLE", "VIRTUAL", "GALA", "GOOGLX", "DRAMB",
  "MUBARAK", "GRAM", "EWYB", "WDCB", "LAB", "COINX", "TST", "PIPPIN", "XLM", "1000PEPE",
  "AMDB", "STX", "BMT", "ESPORTS", "AMZNX", "BASED", "EVAA", "KITE", "JASMY", "PNUT",
  "RKLBB", "TRX", "ZEN", "ARMB", "BABAB", "ETHFI", "BILL", "APT", "LDO", "1000SHIB",
  "HANA", "NOT", "POL", "ORDI", "LITEB", "AIXBT", "EDEN", "AR", "PENGU", "PARTI", "ZK",
  "ARIA", "WIF", "TSMB", "COAI", "LAYER", "OPN", "SWARMS", "PI", "AIGENSYN", "DEEP",
  "LIGHT", "OP", "BANK", "RAVE", "ORDER", "SIREN", "MELANIA", "BERA", "MEME", "DOGS",
  "SPX", "GRIFFAIN", "POPCAT", "LISTA", "RSR", "RED", "VANA", "TOWNS", "AIOT", "1000FLOKI",
  "SAHARA", "ACT", "SEI", "ALLO", "STRK", "USUAL", "BLUR", "KSM", "1MBABYDOGE", "HBAR",
  "MOODENG", "WCT", "SKL", "DUSK", "ALT", "1000BONK", "NEIRO", "RUNE", "MANTA", "IO",
  "BIO", "SUN", "API3", "WLFI", "IN", "MMT", "SAGA", "RARE", "EIGEN", "PROVE", "SONIC",
  "ENJ", "MON", "TRB", "IOTA", "1000SATS", "MOVE", "AIN", "TLM", "DYDX", "PEOPLE", "HIVE",
  "STBL", "AUCTION", "GOAT", "GLM", "TNSR", "BB", "S", "COOKIE", "FRAX", "ME", "MANA",
  "MASK", "AXS", "SIGN", "INIT", "XAI",
];
